version: '3.7'

services:
  # mongodb:
  #   image: mongo:5.0.8
  #   container_name: mongodb
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: admin
  #   restart: always

  api:
    build:
      context: .
    ports:
      - 5000:5000
    environment:
      # - FLASK_ENV=development
      - MONGODB_DB=users
      - MONGODB_HOST=172.28.128.24
      - MONGODB_USERNAME=restapi
      - MONGODB_PASSWORD=mVwzTUVKYKPC6wXD
    restart: always
    # depends_on:
    #   - mongodb
    volumes:
      - ./application:/app/application