name: Deploy Heroku
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flakes pytest
      - name: Run tests
        run: |
          make test
